name: deploy2
on: push
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4.1.6
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4.1.6
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4.1.6
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: echo "Deploying services"


    
    
